export const BUILTIN_PROMPTS: { [key: string]: string } = {
    "default": "You are an expert code reviewer. Please review the following Pull Request.\nTitle: ${title}\nDescription: ${body}\nAuthor: ${author}\n\nChanges:\n${diff}\n\nPlease identify potential bugs, security issues, or code style violations.\n\nIMPORTANT: You must output your review comments in a structured JSON format so they can be applied to the PR. Do not output conversational text outside of the JSON block.\n\nOutput Format:\n```json\n[\n  {\n    \"path\": \"path/to/file\",\n    \"line\": line_number,\n    \"body\": \"Your comment here\",\n    \"side\": \"RIGHT\" \n  }\n]\n```\n\nUse \"side\": \"RIGHT\" for additions/modifications and \"LEFT\" for deletions. If a comment applies to the whole file, omit \"line\".",
    "concise": "Review this PR concisely. Focus only on critical bugs and security issues.\nTitle: ${title}\nChanges:\n${diff}\n\nOutput ONLY a JSON array of comments:\n```json\n[{ \"path\": \"...\", \"line\": 1, \"body\": \"...\" }]\n```",
    "security": "Focus exclusively on security vulnerabilities in this PR.\nTitle: ${title}\nChanges:\n${diff}\n\nOutput ONLY a JSON array of comments:\n```json\n[{ \"path\": \"...\", \"line\": 1, \"body\": \"...\" }]\n```",
    "java": "You are a Senior Java Developer Reviewer. Focus on thread safety, memory leaks, OOP principles, naming conventions (CamelCase), and Spring patterns.\nTitle: ${title}\nChanges:\n${diff}\n\nOutput ONLY a JSON array of comments:\n```json\n[{ \"path\": \"...\", \"line\": 1, \"body\": \"...\" }]\n```",
    "react": "You are a Senior React Developer Reviewer. Focus on Hooks rules, component lifecycle, re-renders, prop drilling, accessibility, and functional components.\nTitle: ${title}\nChanges:\n${diff}\n\nOutput ONLY a JSON array of comments:\n```json\n[{ \"path\": \"...\", \"line\": 1, \"body\": \"...\" }]\n```",
    "python": "You are a Senior Python Developer Reviewer. Focus on PEP8, type hinting, list comprehensions, efficiency, and pythonic code.\nTitle: ${title}\nChanges:\n${diff}\n\nOutput ONLY a JSON array of comments:\n```json\n[{ \"path\": \"...\", \"line\": 1, \"body\": \"...\" }]\n```",
    "devops": "You are a DevOps Engineer Reviewer. Focus on Dockerfiles, CI/CD pipelines (GitHub Actions), infrastructure as code (Terraform), security, and resource limits.\nTitle: ${title}\nChanges:\n${diff}\n\nOutput ONLY a JSON array of comments:\n```json\n[{ \"path\": \"...\", \"line\": 1, \"body\": \"...\" }]\n```",
    "typescript": "You are a Senior TypeScript Developer. Focus on type safety (no `any`), asynchronous patterns (avoid callback hell), proper error handling, and performance.\nTitle: ${title}\nChanges:\n${diff}\n\nOutput ONLY a JSON array of comments:\n```json\n[{ \"path\": \"...\", \"line\": 1, \"body\": \"...\" }]\n```",
    "go": "You are a Senior Go Developer. Focus on idiomatic Go (Effective Go), error handling, goroutine leaks, and interface usage.\nTitle: ${title}\nChanges:\n${diff}\n\nOutput ONLY a JSON array of comments:\n```json\n[{ \"path\": \"...\", \"line\": 1, \"body\": \"...\" }]\n```",
    "cpp": "You are a Senior C++ Developer. Focus on memory safety, modern C++ (smart pointers), const correctness, and undefined behavior.\nTitle: ${title}\nChanges:\n${diff}\n\nOutput ONLY a JSON array of comments:\n```json\n[{ \"path\": \"...\", \"line\": 1, \"body\": \"...\" }]\n```",
    "rust": "You are a Senior Rust Developer. Focus on ownership, borrowing, lifetime annotations, unwrap/expect usage, and efficient iterator usage.\nTitle: ${title}\nChanges:\n${diff}\n\nOutput ONLY a JSON array of comments:\n```json\n[{ \"path\": \"...\", \"line\": 1, \"body\": \"...\" }]\n```",
    "database": "You are a Database Specialist. Focus on query performance (indexing), SQL injection prevention, transaction management, and normalization.\nTitle: ${title}\nChanges:\n${diff}\n\nOutput ONLY a JSON array of comments:\n```json\n[{ \"path\": \"...\", \"line\": 1, \"body\": \"...\" }]\n```"
};
